import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-screen w-full max-w-3xl px-4 py-14 sm:px-6">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: February 2026
      </p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Platform Description
          </h2>
          <p>
            PhaseZero is a two-sided marketplace connecting homeowners and
            contractors with electrical material dealers. The platform provides an
            Bill of Materials calculator aligned with IS 732 standard practice, and
            a Request for Quotation engine. Outputs are informational estimates, not
            certified electrical designs.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Estimates Disclaimer
          </h2>
          <p>
            All estimates generated by the calculator are <strong>approximate</strong>{" "}
            and intended for reference and dealer quoting purposes only. Actual
            material requirements may vary by &plusmn;10-15% depending on site
            conditions. Final specifications must be verified by a licensed
            electrical professional prior to procurement and installation. PhaseZero
            accepts no liability for estimates used without professional
            verification.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Marketplace Terms
          </h2>
          <ul className="ml-4 list-disc space-y-1">
            <li>
              PhaseZero facilitates connections between buyers and sellers but is
              not a party to any transaction.
            </li>
            <li>
              Contact information is shared between parties only after a quote is
              accepted.
            </li>
            <li>
              Dealers are responsible for the accuracy of their quotes, brands
              offered, and delivery timelines.
            </li>
            <li>
              Homeowners are responsible for verifying material specifications
              with their electrician before purchase.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Dealer Obligations
          </h2>
          <ul className="ml-4 list-disc space-y-1">
            <li>
              Provide accurate company information and valid GSTIN where
              applicable.
            </li>
            <li>
              Quote only genuine, BIS-certified electrical materials from
              authorized brands.
            </li>
            <li>
              Honor accepted quotes within the stated delivery timeline.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Limitation of Liability
          </h2>
          <p>
            PhaseZero provides the platform &ldquo;as is&rdquo; without warranties
            of any kind. We are not liable for any damages arising from the use of
            our calculator estimates, marketplace transactions, or dealer
            interactions. Maximum liability is limited to the fees paid to PhaseZero
            in the preceding 12 months.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-semibold text-foreground">
            Contact
          </h2>
          <p>
            For questions about these terms, email{" "}
            <span className="font-medium text-foreground">
              legal@phasezero.in
            </span>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
